#!/bin/sh
ex_ref=$(echo $1 | cut -d/ -f1)
ex_fnm=$(echo $1 | cut -d/ -f2)

sed "/^FT_NAME/s/$/$ex_fnm/" Makefile.template > $ex_ref/Makefile
echo Generated $ex_ref/Makefile
if test ! -f $ex_ref/main.c
then
	sed "s/_ft_name_/$ex_fnm/" main.c.template > $ex_ref/main.c
	echo Generated $ex_ref/main.c
fi
