#!/bin/sh
if test -z "$@"
then
  echo usage: setdeps object_file ...
  exit 1
fi

EDIT_OPERATION='/^DEPS/s/:=.*$/:= '"$@"'/'
SUB_EDIT_OPERATION='/^DEPS/s/:=.*$/:= '"$@"'/'
sed -e "$EDIT_OPERATION" -i '' Makefile
for file in $(git ls-tree -r master --name-only)
do
	sed -e "$EDIT_OPERATION" -i '' $(dirname $file)/Makefile
done
