#!/bin/sh
# deps are object files compiled with the `-c` `gcc` flag.
# They should be located in the root of the repository.

if test -z "$@"
then
  echo usage: setdeps function_name [...]
  exit 1
fi

DEPS1=
DEPS0=
for dep in "$@"
do
	DEPS1="$DEPS \\.\\.\\/$dep.o"
	DEPS0="$DEPS $dep.o"
done
EDIT_OPERATION1='/^DEPS/s/:=.*$/:= '"$DEPS1"'/'
EDIT_OPERATION0='/^DEPS/s/:=.*$/:= '"$DEPS0"'/'

# set deps in root Makefile
echo Updating root Makefile
if sed --version 2>/dev/null | grep 'GNU' > /dev/null
then
	sed -e "$EDIT_OPERATION0" -i '' Makefile
else
	sed -i "$EDIT_OPERATION0" Makefile
fi

# set deps in exercices Makefiles
git_branch=$(git branch --abbrev=0 | grep '^*' | cut -c 3-)
if test $git_branch != master
then
	echo "Warning not in branch master (branch: * $git_branch)"
fi
for file in $(git ls-tree --name-only -r $git_branch)
do
	TARGET_MAKEFILE=$(dirname $file)/Makefile
	echo Updating $TARGET_MAKEFILE
	if sed --version 2>/dev/null | grep 'GNU' > /dev/null
	then
		sed -i "$EDIT_OPERATION1" $TARGET_MAKEFILE
	else
		sed -e "$EDIT_OPERATION1" -i '' $TARGET_MAKEFILE
	fi
	# echo sed -e "$EDIT_OPERATION1" -i '' $TARGET_MAKEFILE
done
